# port
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  # basePath
  servlet:
    context-path: /api

spring:
  application:
    name: monolith
  datasource:
    url: jdbc:postgresql://yukunyuan-tools.cz2o4csgcafy.ap-east-1.rds.amazonaws.com:5432/yukunyuan_tools?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: Xz*ki[7Z!zX:OR!wOmksXNVjEz(F
