aws:
  secretsmanager:
    secretName: rds!db-d1af7ad7-56e7-44ff-bb42-8983f082e2dc

spring:
  application:
    name: migration
  datasource:
    url: jdbc:postgresql://yukunyuan-tools.cz2o4csgcafy.ap-east-1.rds.amazonaws.com:5432/yukunyuan_tools?useUnicode=true&characterEncoding=UTF-8
