spring:
  application:
    name: migration
  datasource:
    url: jdbc:postgresql://localhost:54320/yukunyuan_tools?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 123456
