spring:
  application:
    name: migration
  datasource:
    url: jdbc:postgresql://yukunyuan-tools.cz2o4csgcafy.ap-east-1.rds.amazonaws.com:5432/yukunyuan_tools?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 9NG%T5hee*kwSGWuCAJ:qUMPn~y[
